name: site_web_mobile
description: Minimal pubspec for the site_web mobile Dart package to resolve dependencies used in lib/
environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  http: ^0.13.6

flutter:
  uses-material-design: true
